More type hints and docstrings.
menicgiulia/CPIExtract pull request #1
Opened 2024-07-09 12:08 UTC by alchemistcai

- Add more type annotations.Some may be wrong(input_ids,etc.) as they are related to DataFrame,hard to guess their type.
- Add simple docstrings to public modules,classes,functions for IDE support.
- Alter the default value of `chembl_ids` from `[]` to `None` in `cpiextract.databases.ChEMBL.ChEMBL.interactions`.Mutable default values in function defination is dangerous.

2024-07-12 14:39 UTC, andreapiras00 requested changes
Have some suggestions for PubchemServer.py and corrections for the DataManager classes

2024-07-12 14:39 UTC, andreapiras00 commented on cpiextract/servers/PubchemServer.py
> +    def get_compounds(self, comp: Union[list[str], str], selected_columns: list[str], domain: str='compound', namespace: str='cid') -> pd.DataFrame:
Here you could substitute Union[list[str], str] with the Strs type you defined in typing.py

2024-07-12 14:39 UTC, andreapiras00 commented on cpiextract/servers/PubchemServer.py
> +    def get_synonyms(self, comp: Union[list[str], str], domain: str='compound', namespace: str='cid') -> pd.DataFrame:
Also here you could substitute Union[list[str], str] with the Strs type you defined in typing.py

2024-07-12 14:39 UTC, andreapiras00 commented on cpiextract/data_manager/APIManager.py
> +    def retrieve_raw_data(self, filter_column: str, filter_value: Strs, **kwargs) -> DataFrame:
The correct typing for filter_value should be: list[str | int] | str | int

2024-07-12 14:39 UTC, andreapiras00 commented on cpiextract/data_manager/DataManager.py
> +    def retrieve_raw_data(self, filter_column: str, filter_value: Strs, **kwargs):
The correct typing for filter_value should be: list[str | int] | str | int

2024-07-12 14:39 UTC, andreapiras00 commented on cpiextract/data_manager/LocalManager.py
> +    def retrieve_raw_data(self, filter_column: str, filter_value: Strs, **kwargs) -> pd.DataFrame:
The correct typing for filter_value should be: list[str | int] | str | int

2024-07-12 14:39 UTC, andreapiras00 commented on cpiextract/data_manager/SQLManager.py
> +    def retrieve_raw_data(self, filter_column: str, filter_value: list[str] | str, **kwargs) -> pd.DataFrame:
The correct typing for filter_value should be: list[str | int] | str | int

2024-07-18 13:08 UTC, alchemistcai commented
Done.Thanks for  reviewing.

Also I alter some import statements in ipynb notebooks.

2024-07-23 15:25 UTC, andreapiras00 approved these changes
Looks good to me! Thanks for your contribution

2024-07-23 15:37 UTC, merged